version: '3.8'

services:
  app:
    build: .
    container_name: golang_app
    env_file:
      - .env.overwrite
    expose:
      - "8080"
    depends_on:
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - 8090:8090
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env.overwrite
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env.overwrite
    ports:
      - "5432:5432"
    volumes:
      - cache_storage:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    env_file:
      - .env.overwrite
    ports:
      - "5672:5672" #  AMQP
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  redis:
    image: redis:6.2.19-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  cache_storage:
  minio_data:
  postgres_data:
  rabbitmq_data:
  redis_data:
