version: '3.8'

services:
  app:
    build: ./golang
    container_name: golang_app
    env_file:
      - ../.env
    expose:
      - "8080"
    depends_on:
      - minio
      - postgres

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ../.env
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - auth_template:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    env_file:
      - ../.env
    ports:
      - "5672:5672" #  AMQP
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  redis:
    image: redis:6.2.19-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  minio_data:
  postgres_data:
  rabbitmq_data:
  redis_data:
